# Generated by Django 4.2.18 on 2025-01-21 23:02

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_about_me_collaboraterequest_me'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_me',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
